openapi: 3.0.3
info:
  title: Recommendation Engine
  description: |-
    Example description.
  version: 1.0.0
servers:
  - url: localhost
tags:
  - name: nlp
    description: NLP functions
  - name: user
    description: User interactions
paths:
  /nlp/recommendations:
    get:
      tags:
        - nlp
      summary: Get a recommendation
      description: Get recommendation
      operationId: getRecommendation
      responses:
        '200':
          description: Successful operation
  /categories:
    get:
      tags:
        - user
      summary: Get all categories
      description: Get category
      operationId: createUser
      responses:
        default:
          description: successful operation
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
      xml:
        name: category
